name: Deploy Django Docker App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        docker build -t your-image-name .

      # - name: 'Login to GitHub Container Registry'
      #     uses: docker/login-action@v1
      #     with:
      
      # - name: Push Docker image
      #   run: docker push your-image-name

      # - name: Deploy to server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      #       docker pull your-image-name
      #       docker stop your-container-name || true
      #       docker rm your-container-name || true
      #       docker run -d -p 8000:8000 --name your-container-name your-image-name