services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: $${DB_USER}
      POSTGRES_PASSWORD: $${DB_PASSWORD}
      POSTGRES_DB: $${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data

  celery:
    build: .
    command:
      ["celery", "-A", "auto_app.celery:app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env.prod
      

  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  postgres_data:
  redis_data:
