services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      - ./static:/staticfiles 
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]

  db:
    restart: always
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data

  celery:
    build: .
    command:
      ["celery", "-A", "auto_app.celery:app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env.prod
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./static:/staticfiles
    ports:
      - "80:80" 
    depends_on:
      - web 

volumes:
  postgres_data:
  redis_data:
  static:
  nginx.conf:
