# Generated by Django 5.1.3 on 2024-12-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_app", "0002_rename_user_posting_post_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
    ]
