# Generated by Django 5.1.3 on 2024-12-10 01:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_app", "0003_rename_user_id_post_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="BlueskyProfile",
        ),
    ]
