# Generated by Django 5.1.3 on 2024-12-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
