# Generated by Django 5.1.3 on 2024-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_app", "0004_rename_userprofile_blueskyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="task_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
