# Generated by Django 5.1.3 on 2024-12-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_app", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bluesky_password",
            field=models.CharField(blank=True, null=True),
        ),
    ]
