# Generated by Django 5.1.3 on 2024-12-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_app", "0006_alter_userprofile_bluesky_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.TextField()),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "user_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="auto_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
